{
 "title": "ILERNA - Big Data Aplicado",
 "tags": [
  "bigdata",
  "pipeline"
 ],
 "refresh": "15s",
 "panels": [
  {
   "title": "Total peticiones generadas",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(app_requests_total)" }
   ]
  },
  {
   "title": "Mensajes consumidos por el job",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "job_messages_consumed_total" }
   ]
  },
  {
   "title": "Ventanas escritas en PostgreSQL",
   "type": "stat",
   "gridPos": { "x": 12, "y": 0, "w": 6, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "job_windows_flushed_total" }
   ]
  },
  {
   "title": "Errores de escritura en BD",
   "type": "stat",
   "gridPos": { "x": 18, "y": 0, "w": 6, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "job_db_errors_total" }
   ]
  },
  {
   "title": "Tasa de producción vs consumo (msg/s)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 4, "w": 12, "h": 8 },
   "targets": [
    { "expr": "rate(app_requests_total[1m])", "legendFormat": "Generado ({{http_status}})" },
    {
     "expr": "rate(job_messages_consumed_total[1m])",
     "legendFormat": "Consumido por job"
    }
   ]
  },
  {
   "title": "Tasa de errores HTTP 500 (msg/s)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 4, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(app_requests_total{http_status=\"500\"}[1m])",
     "legendFormat": "Errores 500/s"
    }
   ]
  },
  {
   "title": "Transacciones por ventana de 30s",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 12, "w": 12, "h": 8 },
   "targets": [
    { "expr": "job_last_window_transactions", "legendFormat": "Transacciones" }
   ]
  },
  {
   "title": "Duración real de ventana (segundos)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 12, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, rate(job_window_duration_seconds_bucket[5m]))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, rate(job_window_duration_seconds_bucket[5m]))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "Logs del generador (app.log)",
   "type": "logs",
   "gridPos": { "x": 0, "y": 20, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/app/app.log\"}"
    }
   ]
  }
 ]
}